### ISSUE TITLE
Support game controllers for ROM games

### ISSUE THREAD

**Issue by hellpe** [Kekun/gnome-games#156]
Currently, I can't use my Xbox 360 wired controller to play my NES or SNES games.

Since this is a very common type of controller, and it's sharing the same button layout as the SNES gamepad, a default setup should be provided for NES and SNES games to work with the Xbox 360 controller, at least.

(other gamepad to consider: Wii Classic Controller, which is natively supported by the kernel IIRC)

**Comment by corebots** [comment]
I'm using a regular cheap usb controller with some emulators but they are difficult to configure. do you plan to support generic controllers or only popular ones like the xbox, ps controller, etc.... ?

**Comment by Kekun** [comment]
I plan to support both, the famous ones may be supported out of the box.
