### ISSUE TITLE
Some SNES titles are badly rendered

### ISSUE THREAD

**Issue by hellpe** [Kekun/gnome-games#160]
Not sure what's going on here, but here's how `Chrono Trigger (USA).sfc` (from planetemu.net) looks like on Games:
![capture d ecran de 2015-09-15 22-51-50](https://cloud.githubusercontent.com/assets/1238320/9889789/7cb6f24a-5bfc-11e5-8a83-10886e1b1fff.png)
![capture d ecran de 2015-09-15 22-53-31](https://cloud.githubusercontent.com/assets/1238320/9889811/9a81e4b0-5bfc-11e5-9f40-5d3b5412e9b0.png)

Terminal says this:
`(gnome-games:21770): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()`

**Comment by Kekun** [comment]
Currently the SNES games' titles are taken from the ROM's header, which isn't at the same position for a LoROM or a HiROM. If the ROM is in the HiROM format whatever bytes are where the title is in a LoROM are used as a title, which end up in a messed up title.

Extracting the title from SNES ROM header is just a bad idea.

**Comment by Kekun** [comment]
Fixed by f6696081cbe4c8c15132a1924924dd195c2456ad

The filename is now used as the title.
