### ISSUE TITLE
Is jhbuild.modules still needed?

### ISSUE THREAD

**Issue by sebn** [Kekun/gnome-games#162]
Can I remove it?

**Comment by sebn** [comment]
(and update HACKING instructions accordingly?)

**Comment by Kekun** [comment]
Oh I didn't notice we still have it, yeah sure you can remove it.

**Comment by meghprkh** [comment]
Why was this removed? I am unable to `jhbuild build gnome-games` currently

**Comment by Kekun** [comment]
It have been merged into the [gnome-world moduleset](https://git.gnome.org/browse/jhbuild/tree/modulesets/gnome-world.modules), you have to add it to your jhbuildrc.
