### ISSUE TITLE
Can't list Steam games warning

### ISSUE THREAD

**Issue by hadess** [Kekun/gnome-games#166]
```
** (gnome-games:31763): WARNING **: application.vala:96: Can't list Steam games: File '/home/hadess/.steam/registry.vdf' doesn't exist.
```

I don't have Steam installed, and this shouldn't be a warning.

**Comment by Kekun** [comment]
If `warning` isn't the correct log level to use, which one should it be? Should it be `message`, or `info`, or even a simple print to stderr or stdout? The lines between the different GLib log levels are a bit fuzzy for me.

**Comment by hadess** [comment]
debug is good enough, and you can enable printing it, either programmatically, using `g_log_default_handler()`, or through an environment variable `G_MESSAGES_DEBUG=all`
