### ISSUE TITLE
xdg-app build

### ISSUE THREAD

**Issue by pdureau** [Kekun/gnome-games#168]
Thanks a lot for your hard work and the first release. This app is a dream coming true.

Is it possible to build an xdg-app repo for Gnome Games ?  The Gnome 3.18 runtime is already available.

Sources : 
- https://wiki.gnome.org/Projects/SandboxedApps
- Gnome Runtime : https://mail.gnome.org/archives/gnome-os-list/2015-September/msg00004.html
- An example of xdg-app building script : https://github.com/alexlarsson/nightly-build-apps

**Comment by pdureau** [comment]
Hello,
I started the work on this issue there: https://github.com/pdureau/nightly-build-apps
The building and the deployment work well. 

But I get a "No games found" message on the Gnome games app. Maybe Tracker can not get out the sandbox. I will take a look on that later.

**Comment by Kekun** [comment]
Could we chat about it on IRC?

**Comment by pdureau** [comment]
A new commit allows Gnome Games to access to Tracker via the Session Bus. Some games are found, but there is no access to the emulators binaries (because, in an xdg-app, /usr/ is the runtime only).

**Comment by pdureau** [comment]
On the master HEAD (commit 613b3811063ffeb36c97d8170c2ec68766d4a7fa), i get thoses errors while running xdg-app run org.gnome.Games: 

``` bash
(gnome-games:2): GLib-CRITICAL **: g_utf8_collate: assertion 'str1 != NULL' failed
** (gnome-games:2): CRITICAL **: games_desktop_tracker_query_check_executable: assertion 'app_info != NULL' failed
(gnome-games:2): GLib-GIO-CRITICAL **: g_app_info_get_icon: assertion 'G_IS_APP_INFO (appinfo)' failed
```

**Comment by Kekun** [comment]
Games is now package as an xdg-app here: https://github.com/alexlarsson/gnome-apps-nightly/blob/master/org.gnome.Games.json
