### ISSUE TITLE
Steam games not detected due to casing mismatch.

### ISSUE THREAD

**Issue by ghost** [Kekun/gnome-games#169]
Hello

I see steam-game.vala is searching for `appid`, which it can't find in my manifest files because Steam decided to name them `appID` instead (with different casing).

Renaming the key makes the game show up correctly.

Thanks in advance

**Comment by Kekun** [comment]
I encountered some case differences between several Steam installs and Games take them into account, but not this one yet, thanks.

**Comment by muflone** [comment]
Confirmed here, all my games have appID in the manifest file
