### ISSUE TITLE
Gamepad and Joystick configuration interface

### ISSUE THREAD

**Issue by nekohayo** [Kekun/gnome-games#171]
This is something I've been dreaming of for a decade. I'd like to have a nice GUI to calibrate and map buttons on gamepads, joysticks, etc. With the ability to save and export profiles, and apply them to multiple devices.

Something that would work everywhere... and maybe not just for games but even for controlling the mouse cursor & clicks in GNOME in general (or for a 10-feet interface). Could be implemented as the link between Games and GNOME Control Center. And maybe define that as some sort of GNOME/freedesktop standard library/API that we can encourage game devs (and Valve) to support.

Type of devices I own for testing:
- XBox (1st gen) controller, with USB adapter
- Joypad USB adapter for two simultaneous Playstation (PSOne and PS2) controllers, with normal controllers and dance mats

**Comment by Kekun** [comment]
I would _love_ to have such a thing, that's clearly something missing in GNOME.

Games is obviously not where the bug lies but I have no problem keeping the discussion here.

**Comment by Kekun** [comment]
It could probably be done in conjunction with Web so it can support the [web gamepad API](http://www.w3.org/TR/gamepad/).

**Comment by hadess** [comment]
Full link:
https://w3c.github.io/gamepad/#remapping
