### ISSUE TITLE
The type name `ListModel' could not be found when compiling from sources

### ISSUE THREAD

**Issue by jordimas** [Kekun/gnome-games#183]
System: Ubuntu 15.04 with Vala 0.26.2

When compiling the app I gives the following errors;

ui/application.vala:4.10-4.18: error: The type name `ListStore' could not be found
    private ListStore collection;
            ^^^^^^^^^
ui/application-window.vala:37.28-37.36: error: The type name`ListModel' could not be found
    public ApplicationWindow (ListModel collection) {
                              ^^^^^^^^^
ui/collection-icon-view.vala:16.10-16.18: error: The type name `ListModel' could not be found
    private ListModel _model;
            ^^^^^^^^^
ui/collection-icon-view.vala:17.9-17.17: error: The type name`ListModel' could not be found
    public ListModel model {
           ^^^^^^^^^
ui/collection-icon-view.vala:17.9-17.17: error: The type name `ListModel' could not be found
    public ListModel model {
           ^^^^^^^^^
ui/collection-icon-view.vala:17.9-17.17: error: The type name`ListModel' could not be found
    public ListModel model {
           ^^^^^^^^^
ui/content-box.vala:74.21-74.29: error: The type name `ListStore' could not be found
    public ContentBox (ListStore collection) {
                       ^^^^^^^^^
ui/content-box.vala:35.9-35.17: error: The type name`ListModel' could not be found
    public ListModel collection {
           ^^^^^^^^^
ui/content-box.vala:35.9-35.17: error: The type name `ListModel' could not be found
    public ListModel collection {
           ^^^^^^^^^
ui/content-box.vala:35.9-35.17: error: The type name`ListModel' could not be found
    public ListModel collection {
           ^^^^^^^^^
Compilation failed: 10 error(s), 0 warning(s)

**Comment by Kekun** [comment]
This seems to be an Ubuntu specific library or vapi version problem. Not sure how I could help you there as I don't use it. =/

**Comment by jordimas** [comment]
Which is the minimum vapi version needed? 

Which linux distribution version do you use to compile the project?

Jordi,

**Comment by Kekun** [comment]
GListStore has been added in 2.44: [https://developer.gnome.org/gio/unstable/GListStore.html](https://developer.gnome.org/gio/unstable/GListStore.html).

I developed the project under Fedora 22, but that's not relevant as I developed it using [JHBuild](https://wiki.gnome.org/Projects/Jhbuild) which is the recommended way to play with the dev version of Games and should work fine on any non archaic distro.

Hoping it will help. =)
