### ISSUE TITLE
Providing Gnome-Games in Fedora 24

### ISSUE THREAD

**Issue by fbruetting** [Kekun/gnome-games#296]
Hi, it is stated on the website, that GG is available in Fedora, but sadly it isn't. Could you include it in the default F24 repo? Would be nice!

**Comment by Kekun** [comment]
Hi, thanks for the info, this page has been updated.

Unfortunately I can't add Games to the Fedora repo myself as I don't have time to do so now, I recommend you to reach a Fedora packager instead, I'll be happy to help if needed.
