### ISSUE TITLE
Make it possible to run from discs

### ISSUE THREAD

**Issue by hadess** [Kekun/gnome-games#297]
When we support PSX games through a free BIOS, we should make it possible to use real discs to play the games, even if we require to "rip" those discs first, such as done there:
http://www.pandorawiki.org/Creating_images_of_PSX_games_using_Linux

**Comment by Kekun** [comment]
It looks like something we want to support, in a way or another.

We could present ripping the disk as installing the game, though if we do so we need a good design to support multi-disc games.

**Comment by hellpe** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=771412

**Comment by hellpe** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=771412
