### ISSUE TITLE
Some game covers are not retrieved

### ISSUE THREAD

**Issue by hellpe** [Kekun/gnome-games#325]
I'm having this specific issue with Septentrion (`Septentrion (Japan).sfc`), which [can be found in TheGamesDB](http://thegamesdb.net/game/5961) by typing "SOS" (the US version) in the search field, but not "Septentrion", even if the game is labeled as "SOS - also known as Septentrion".

I guess this is related to the way TheGamesDB handles regional differences (it actually [does not handle that at all](http://forums.thegamesdb.net/topic/101/release-dates-and-regions/2)) Should we get in touch with them to see how there's planning to do this, or could we use another solution?

**Comment by Kekun** [comment]
Can you please refile this bug over at Bugzilla?

**Comment by hellpe** [comment]
It already has ;) https://bugzilla.gnome.org/show_bug.cgi?id=771277
