### ISSUE TITLE
"Resume last game" dialog is misleading

### ISSUE THREAD

**Issue by hellpe** [Kekun/gnome-games#69]
Currently, when leaving a ROM game, Games conveniently makes a savestate to allow the user to restart her game at this point, just like in recent editions of old games on Wii U and 3DS. So far, so good.

So when such a ROM is opened again in Games, it displays a screenshot of the saved state (which tells the user where he left off previously), and pops up a dialog asking to "Resume last game?", leaving the user with three options:
- "Resume" (highlighted), which effectively resumes the game at the saved point
- "Main Menu", which deletes the savestate and resets the game
- "Cancel", which closes the game and returns to Games' main screen

The problem here is with the "Main Menu" button, which suggests the user that she will go back to some kind of "menu", whereas it actually destroys her save point. That button should be named more accurately. Maybe something like "Discard", "Reset" or "Start Over"?

![capture d ecran de 2015-08-28 02-17-01](https://cloud.githubusercontent.com/assets/1238320/9536410/a857c8dc-4d2b-11e5-8835-2477b71092f4.png)

**Comment by Kekun** [comment]
Fixed without mentioning this bug entry.
